services:
    ai-agent:
        build: .
        ports:
          - '8502:8502'
        env_file:
          - .env
        volumes:
          - ./config:/app/config
        environment:
          - PYTHONUNBUFFERED=1
        command: streamlit run main.py --server.port 8502 --server.headless true
